### ISSUE TITLE
Cluster configuration???

### ISSUE THREAD

**Issue by franklupo** [Corsinvest/cv4pve-barc#18]
Hello to all,

Now the cron file is in /etc/cron.d.
My idea is to move it to /etc/pce/eve/barc/barc.cron so that it is replicated across the entire cluster (corosync).
In this way you can have a unique configuration and with the --only-local parameter the node will only backup its vm, naturally following the rules of the --vmid.
If vm is moved to another node, there will always be backup without having to reconfigure.

What do you think?

Thank you all

**Comment by Ogy** [comment]
Hello,
thanks for suggestion.
I'm using it quite differently.
I have mounted remote filesystem on one node, where is in place cron, so 
I will everytime use cron on one node.
Due to RDB it doesn't matter where VM runs. What the --only-local should 
do ? Is there any reason to have synchronized cron over all nodes (i can 
imagine one - the node failure)
What would be really interesting would be to use hook script to check or 
mount that remote FS (OK, i've just read docs,and there is --script )

I have two questions for you...
     1) Today, whole Data Center went down, for awhile, before cron 
started backup.
         so remote FS has been disconnected, then BARC started
         due to low space on local "/" the backup failed
             the question is: will next backups be "corrupted" ? (i have 
--keep 31(it will miss one backup for recovery(am I correct?)))
     2) can you, please, modify the lock setting? or introduce something 
like backup queue
             snapshot function has been modified to do snapshots of all 
disks of a VM at once (again thanks for it !).
             so if i'm correct, there is no needs to lock (let fail) 
other sheduled backups (other VMs)
                     yeah, we need to let backup fail - when its exports 
take more than 23:59 hours
             i have few TB VMs, so one full backup is blocking backups 
of small VMs.
                 I can recommend to use ZFS as storage for backups, 
because it doesn't store zeroes
                     Unfortunately when I'm doing recovery, the !@#$ 
zeroes are being transfered over network, so it takes a lot of time.

Many thanks for your time and great BARC
Thanks
Tomas



Dne 12.10.2017 v 17:50 Daniele Corsini napsal(a):

**Comment by franklupo** [comment]
Hi Tomas,
what I'm doing and unify configurations so that each host runs its exports, this to distribute the load. It will remain possible to export everything from a host.

> 
>    1) Today, whole Data Center went down, for awhile, before cron
> started backup.
>          so remote FS has been disconnected, then BARC started
>          due to low space on local "/" the backup failed
>              the question is: will next backups be "corrupted" ? (i have
> --keep 31(it will miss one backup for recovery(am I correct?)))

Backups may be corroded.

>   2) can you, please, modify the lock setting? or introduce something
> like backup queue
>              snapshot function has been modified to do snapshots of all
> disks of a VM at once (again thanks for it !).
>              so if i'm correct, there is no needs to lock (let fail)
> other sheduled backups (other VMs)
>                      yeah, we need to let backup fail - when its exports
> take more than 23:59 hours
>              i have few TB VMs, so one full backup is blocking backups
> of small VMs.

Ok, I remove the backup check file in progress.

Best regards

**Comment by gardar** [comment]
How about some communication between barc agents in the cluster? 

* If you have one node that backs everything up and that node goes down then it would be good if you could get another node to take it's place and do the backups.
* Communication would be good for doing parallel backup jobs without doing duplicate backups of the same vm's
* It would also be good if you wanted your node with the lowest load to take care of the backups.
* etc.

**Comment by franklupo** [comment]
Hi,
in new version using api.

Best regards
